name: Python + frontend CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python_prepare
      - name: Build Frontend
        env:
          CI: false # needed otherwise dependencies warnings stop the job
          REACT_APP_RAINBOW_PROJECT_ID: ${{ secrets.REACT_APP_RAINBOW_PROJECT_ID }}
        run: yarn --cwd python_web3_wallet/frontend build
      - name: Cache frontend build
        uses: actions/cache@v4
        with:
          path: python_web3_wallet/frontend/build
          key: frontend-build-${{ github.sha }}

  build_python:
    needs: [build_frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python_prepare
      - name: Restore frontend build
        uses: actions/cache@v4
        with:
          path: python_web3_wallet/frontend/build
          key: frontend-build-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Run poetry build
        run: poetry build -f wheel