name: Python CD

on:
  push:
    branches:
      - gabriel/poetry
  release:
    types: [ published ]

jobs:
  publish-pypi-package:
    #if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      #- name: Verify the tag version in the pyproject.toml
      #  run: grep -q "version = \"${{ github.event.release.tag_name }}\"" pyproject.toml || exit 1
      #  shell: bash
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: ./.github/actions/python_prepare
      - name: Build Frontend
        run: npm run build --prefix python_web3_wallet/frontend
      - name: Build and Publish
        run: poetry publish -p ${{ secrets.PYPI_TOKEN }} -u "__token__" --build
        shell: bash